### PR TITLE
Compile

### PR DESCRIPTION
**Pull request by stdavis**
I've got it compiling without errors but it's still not quite right. I'm getting this on http://localhost:9000/blog/:
image

I'm submitting this PR in hopes that it will be helpful. Totally understand if it's in the wrong direction. I've had no experience with harp/jade.

### CODE REVIEW

**Comment by remy** [comment]
Thanks for the work - I'll check this out now and see if I can get it live.

**Comment by remy** [comment]
I'm trying this branch locally, running with node@7 and it compiles (and runs) without errors, but the markup is hosed (not your fault, just a fault in the harp deps I think):

```
<static>= ''</static><pagetitle>= siteTitle</pagetitle><prefix>= repeat('.', current.path.length).split('..').join('../')</prefix><!DOCTYPE html>…
```

It's obviously messed up the compile from the JS in the index.jade file:

```
static = ''
if environment == "production"
  static = 'https://learn.jsbin.com'
if environment == "test"
  static = 'http://localhost:9000'
```

**Comment by stdavis** [comment]
@remy: I made a bit more progress this morning. It's starting to look better. Take another look and let me know what still needs to be fixed.

**Comment by stdavis** [comment]
@remy: I made more progress this morning. It's starting to look better. Take another look, when you get a minute, and let me know what still needs to be fixed.

**Comment by remy** [comment]
Thank you so much for the PR. It's now been fixed and deployed thanks to another effort here: https://github.com/jsbin/learn/pull/94 - I'm very grateful to have external contributions to get this running again ❤️

**Comment by stdavis** [comment]
Glad to see another fellow GIS-er contributing.

**Pull request closed without merging**
